const fs = require("fs");
const { createCanvas } = require("canvas");
const sizes = [192, 512];
sizes.forEach(size => {
  const canvas = createCanvas(size, size);
  const ctx = canvas.getContext("2d");
  const gradient = ctx.createLinearGradient(0, 0, size, size);
  gradient.addColorStop(0, "#0C2C56");
  gradient.addColorStop(1, "#005C5C");
  ctx.fillStyle = gradient;
  ctx.beginPath();
  ctx.arc(size/2, size/2, size/2, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = "#FFFFFF";
  ctx.font = "bold " + (size * 0.4) + "px sans-serif";
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText("TF", size/2, size/2);
  fs.writeFileSync("public/icon-" + size + ".png", canvas.toBuffer("image/png"));
  console.log("Created icon-" + size + ".png");
});
const maskSize = 512;
const canvas = createCanvas(maskSize, maskSize);
const ctx = canvas.getContext("2d");
const gradient = ctx.createLinearGradient(0, 0, maskSize, maskSize);
gradient.addColorStop(0, "#0C2C56");
gradient.addColorStop(1, "#005C5C");
ctx.fillStyle = gradient;
ctx.fillRect(0, 0, maskSize, maskSize);
ctx.fillStyle = "#FFFFFF";
ctx.font = "bold " + (maskSize * 0.3) + "px sans-serif";
ctx.textAlign = "center";
ctx.textBaseline = "middle";
ctx.fillText("TF", maskSize/2, maskSize/2);
fs.writeFileSync("public/icon-maskable.png", canvas.toBuffer("image/png"));
console.log("Created icon-maskable.png");
